1-1: 1-1.cpp
	# stattic_assert example
	g++ -std=c++1z 1-1.cpp -o 1-1

1-2: 1-2.cpp
	# enable if example
	g++ -std=c++1z 1-2.cpp -o 1-2
	
1: 1.cpp
	# run well when we remove the double
	g++ -std=c++1z 1.cpp -o 1
	./1

2: 2.cpp 
	# average problem
	g++ -std=c++1z 2.cpp -o 2
	./2

3: 3.cpp 
	# has virtual function
	g++ -std=c++1z 3.cpp -o 3
	./3

4: 4.cpp 
	# arguments count error check 
	g++ -std=c++1z 4.cpp -o 4
	./4

5: 5.cpp 
	# Typelist
	g++ -std=c++1z 5.cpp -o 5
	./5


